name: cd
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: DOCKER_BUILDKIT=1 docker compose --file docker/compose/docker-compose.yml up -d
      - name: Test
        run: docker run --network container:openmetadata appropriate/curl -s --retry 10 --retry-connrefused http://openmetadata.example.com:8585/